"""add: on_draft attr to product

Revision ID: 0b68b274f2df
Revises: 252955a8cb95
Create Date: 2024-05-30 16:40:40.198379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b68b274f2df'
down_revision = '252955a8cb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_draft', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('on_draft')

    # ### end Alembic commands ###
