"""add: orders and cart table]

Revision ID: 0f4544d9896b
Revises: 0b68b274f2df
Create Date: 2024-06-02 04:05:30.724611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4544d9896b'
down_revision = '0b68b274f2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('cusomization_value', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'COMFIRMED', 'COMPLETED', 'IN_PRGRESS', 'DELIVERED', name='orderStatus'), nullable=False),
    sa.Column('order_progress', sa.Enum('AWAITING_COMFIRMATION', 'MATERIAL_SOURCING', 'CUTTING', 'SEWING', 'IRONING', 'PACKAGING', name='orderProgress'), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('carts')
    # ### end Alembic commands ###
