"""change_made_to_message_Nullable_True

Revision ID: 1f638ca55860
Revises: e8bc91e1285d
Create Date: 2024-07-10 00:07:25.431329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f638ca55860'
down_revision = 'e8bc91e1285d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
