"""add: tailor business information and profile pics url

Revision ID: 252955a8cb95
Revises: 48c87a6a6213
Create Date: 2024-05-29 07:27:24.718149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252955a8cb95'
down_revision = '48c87a6a6213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cac_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('about', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailors', schema=None) as batch_op:
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('about')
        batch_op.drop_column('cac_number')

    # ### end Alembic commands ###
