"""remove product_id from review

Revision ID: 4d08d31ec3df
Revises: b1ead3cdf61a
Create Date: 2024-06-20 15:56:51.852773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d08d31ec3df'
down_revision = 'b1ead3cdf61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
