"""fix: typo in order status

Revision ID: 8541fb429a51
Revises: b303255e43a5
Create Date: 2024-06-15 12:53:33.354516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8541fb429a51'
down_revision = 'b303255e43a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'COMFIRMED', 'COMPLETED', 'IN_PRGRESS', 'DELIVERED'),
               type_=sa.Enum('PENDING', 'COMFIRMED', 'COMPLETED', 'IN PROGRESS', 'DELIVERED', name='orderStatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'COMFIRMED', 'COMPLETED', 'IN PROGRESS', 'DELIVERED', name='orderStatus'),
               type_=mysql.ENUM('PENDING', 'COMFIRMED', 'COMPLETED', 'IN_PRGRESS', 'DELIVERED'),
               existing_nullable=False)

    # ### end Alembic commands ###
