"""update: order status and stages

Revision ID: b303255e43a5
Revises: 20dc295f4e6c
Create Date: 2024-06-15 00:20:05.200406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b303255e43a5'
down_revision = '20dc295f4e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'COMFIRMED', 'COMPLETED', 'IN_PRGRESS', 'DELIVERED', name='orderStatus'), nullable=False))
        batch_op.add_column(sa.Column('stages', sa.JSON(), nullable=False))
        batch_op.drop_column('order_progress')
        batch_op.drop_column('order_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status', mysql.ENUM('PENDING', 'COMFIRMED', 'COMPLETED', 'IN_PRGRESS', 'DELIVERED'), nullable=False))
        batch_op.add_column(sa.Column('order_progress', mysql.ENUM('AWAITING_COMFIRMATION', 'MATERIAL_SOURCING', 'CUTTING', 'SEWING', 'IRONING', 'PACKAGING'), nullable=False))
        batch_op.drop_column('stages')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
