"""add: saved_items attr to user

Revision ID: c566990de72d
Revises: 68a20862b7f5
Create Date: 2024-06-23 21:07:16.515873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c566990de72d'
down_revision = '68a20862b7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('saved_items')

    # ### end Alembic commands ###
